apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: cluster-config
spec:
  targetNamespace: nginx
  releaseName: nginx-ingress-controller
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: cluster-config
      version: "4.10.1" # Check Artifact Hub or `helm search repo` for latest
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    controller:
      service:
        type: NodePort
      extraArgs:
        # Optional: Customize as needed
        enable-ssl-passthrough: ""
      admissionWebhooks:
        enabled: true
